name: Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: Restore dependencies
        run: dotnet restore ./SpanLinq.sln
      - name: Build
        run: dotnet build SpanLinq/SpanLinq.csproj- --configuration Release --no-restore
      - name: Test
        run: dotnet test ./SpanLinq.sln --configuration Release --no-restore