name: Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x.x
      - name: Restore dependencies
        run: |
          ls -a
          cd SpanLinq
          dotnet restore
      - name: Build
        run: |
          ls -a
          cd SpanLinq
          dotnet build --no-restore
      - name: Test
        run: |
          cs ./SpanLinq.Tests
          dotnet test --no-build --verbosity normal