name: Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x
      - name: ls
        run: ls
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal